### ISSUE TITLE
Does this sample support transfer gzipped content to browser client?

### ISSUE THREAD

**Issue by dlintw** [artificerpi/vfsgen-sample#1]
I try to put a 2MB.html in assets directory and use chrome to check the load size. I found it transfer about 2MB instead of gzipped size.

**Comment by qtopie** [comment]
Refer to [the documentation of vfsge](https://github.com/shurcooL/vfsgen/blob/master/README.md#additional-embedded-information)  Your tested files may not be worth gzip compressing. 
And here's the comment in codes `/ If compressed file is not smaller than original, revert and write original file.`

**Comment by qtopie** [comment]
I've just check the gzip compression with static files in this project: https://github.com/mdn/html-examples, and it works well.

Please check whether following lines exist in the `assets_vfsdata.go` after `go generate`:
```go
func (f *vfsgen۰CompressedFileInfo) GzipBytes() []byte {
	return f.compressedContent
}
```

Don't use single html file to test compression, it might not be worth gzip compressing.

**Comment by dlintw** [comment]
I use Linux's sparse file to test, so, it is compressable(all zeros)
```
cd $GOPATH/src
mkdir -p github.com/artificerpi
cd github.com/artificerpi
git clone https://github.com/artificerpi/vfsgen-sample
cd vfsgen-sample/
make setup
make
dd if=/dev/zero of=data/assets/2M.html bs=1M count=2
dd if=/dev/zero of=data/assets/100M.html bs=1M count=100
make
dd if=/dev/zero of=data/assets/2M.html bs=1M count=2
./vfsgen-sample
# use browser to test http://localhost:7070/2M.html
# or http://localhost:7070/100M.html
```
I've checked the output file, it is generated compressed file. The executable file size is about 7MB only
```
grep 'CompressedFileInfo.*GzipByte' data/assets_vfsdata.go

output:
func (f *vfsgen۰CompressedFileInfo) GzipBytes() []byte {
```

**Comment by qtopie** [comment]
Ok. Close this issue.

**Comment by dlintw** [comment]
What I mean is the executable file is compressed, but the transfer size is still large, it will takes the long time to transfer the HTML to browser.  If this example shows how to just transferring the compressed data to browser.

**Comment by qtopie** [comment]
HTML content is compressed but not cached, it may take more time to render. For this tool, the main purpose is to create embedded executable binary file. If you have any questions about the principle behind, pls refer to the codes of vfsgen.

BTW, you should note that the http sever has not set gzip support.
